# Numpy
- based on https://github.com/mephistopheies/mlworkshop39_042017/blob/master/0_python_intro/%D0%A3%D0%BF%D1%80%D0%B0%D0%B6%D0%BD%D0%B5%D0%BD%D0%B8%D1%8F.ipynb

<img src="trainings1.jpg" />

## Task 0
- import numpy

In [2]:
import numpy as np
from scipy import stats

In [ ]:
## Task 1
- print version of numpy

## Task 2
- create 1d vector of zeros of size 10

In [5]:
x= np.zeros((10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## Task 3
- create 1d vector filled with ones of size 10

In [6]:
x= np.ones((10))

## Task 4
- create 1d vector filled with ones of size 10,

In [ ]:
x= np.ones((10))

## Task 5
- crete 1d vector filled with numbers from 10 to 49

In [10]:
x= np.arange(10, 50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


## Task 6
- create any 1d vector, then reverce it, such that last element will be on the first position

In [12]:
x= np.arange(1,11)
np.flip(x)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

## Task 7
- create 2d 3x3 array / matrix, filled with numbers from 0 to 8

In [14]:
x = np.arange(9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## Task 8
- create 3x3 matrix filled with ones

In [50]:
x= np.ones((3,3))
print(x)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## Task 9
- create 3x3 matrix filled with random numbers

In [20]:
x= np.random.rand(3,3)
print(x)

[[0.46087257 0.434775   0.42981568]
 [0.60836212 0.46228634 0.74020983]
 [0.50399761 0.05190704 0.49878231]]


## Task 10
- create 3x3x3 array filled with random numbers

In [21]:
x= np.random.rand(3,3,3)
print(x)

[[[0.35684785 0.49159015 0.61914887]
  [0.25482427 0.32803351 0.17869947]
  [0.78378724 0.95139503 0.97666875]]

 [[0.86681226 0.86692161 0.40801596]
  [0.95756438 0.91842747 0.85823179]
  [0.00998259 0.08839642 0.16210958]]

 [[0.05741495 0.34835396 0.41051068]
  [0.3988042  0.74727698 0.66062201]
  [0.87820329 0.79462573 0.22605739]]]


## Task 11
- create 10x10 matrix filled with random numbers and find minimal and maximal elements

In [68]:
x= np.random.rand(10,10)
np.amax(x), np.amin(x)

(0.9945417417294653, 0.0020265670205795727)

## Task 12
- create a random 1d vector of size 30 and find average of them

In [45]:
x=np.random.rand(30)
np.mean(x)

0.5181175366071895

## Task 13
- create 5x5 matrix, which has ones on a "frame" and zeros inside

In [51]:
x= np.ones((5,5))
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Task 14
- create 8x8 matrix
- fill it with ones and zeros in a "chess" order
- **don't use** `tile` funtion

## Task 15
- create 8x8 matrix
- fill it with ones and zeros in a "chess" order
- **use** `tile` funtion

In [11]:
a = np.array([0, 1])
np.tile(a, (8,8))

array([[0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1]])

## Task 16
- create two random matrices 5x3 and 3x2
- multiply them

In [84]:
x= np.random.rand(5,3)
y= np.random.rand(3,2)
z= np.matmul(x,y)
print(z)

[[0.26548285 0.45353443]
 [0.49564991 0.94175858]
 [0.25504463 0.42525288]
 [0.33114599 0.58738976]
 [0.66926588 1.19721609]]


## Task 17
- create array of size 100 filled with random numbers from 0 to 10
- chenge sign of all numbers which are in a range between 3 and 8

In [50]:
x= np.random.randint(10, size=100)
m= (x>2)*(x<9)
x[m]*=-1
print(x)

[-5  2 -4  9 -7 -7  0 -8 -3 -4 -7 -4  1  9 -7 -8 -4 -8  1 -8  0  2 -5 -7
  1  1  9 -4 -4 -5 -8  2  2 -3 -4  2  1 -5 -3 -5  9 -6 -6 -3 -3 -4  1  0
  9  1 -5 -5 -3 -8 -4 -5 -8  1 -7  1  0 -4 -7 -7 -6  9  2 -7  0 -5 -6  1
 -7 -4 -8 -4 -7 -6 -6 -4  2 -3  1 -4  0 -7 -5 -7  0 -8  2 -6  0  0 -6 -4
 -5 -7  1 -5]


## Task 18
- create a matrix 5x5 such that each row would be a 1d array filled with numbers from 0 to 4

In [52]:
x = np.zeros((5,5)) + np.arange(5)
print(x)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


## Task 19
- create 1d vector of size 100 filled with random values from range 0-1, excluding boundary values (no exact 0/1)

In [68]:
x= np.random.uniform(low=0.1, high=0.9, size=100)
print(x)

[0.20738232 0.71714279 0.79901651 0.61630266 0.72276098 0.29329719
 0.88543301 0.26928256 0.12624636 0.46123938 0.69274989 0.24531198
 0.53396516 0.58593321 0.15882454 0.58232898 0.65195198 0.83469111
 0.79861625 0.17358819 0.5084962  0.49742638 0.49837736 0.64585535
 0.60877503 0.38646785 0.71502605 0.39787882 0.70000748 0.69623086
 0.75848306 0.18573316 0.87726152 0.40643054 0.35775943 0.18509037
 0.83440933 0.17601638 0.75889477 0.47979402 0.59026024 0.62226515
 0.26247158 0.60095193 0.87158595 0.39083803 0.27800973 0.87851577
 0.44126695 0.78046742 0.16594012 0.70030767 0.36711257 0.76663822
 0.24179784 0.41107012 0.21670804 0.53683989 0.47679625 0.88156451
 0.81563517 0.58884582 0.4836545  0.10213058 0.28959983 0.424178
 0.61151772 0.22906675 0.76625306 0.64875713 0.37478357 0.15912053
 0.38385475 0.44595583 0.77452887 0.37487744 0.28467345 0.61940453
 0.31115973 0.74974981 0.50409552 0.39921607 0.65716601 0.72117727
 0.23174359 0.28058946 0.11304381 0.37557161 0.18044599 0.592725

## Task 20
- create a 10x2 random matrix filled with number from range 0-100
- consider it as points in Cartesian plain
- convert to polar system of coordinates

In [19]:
m= np.zeros((10,2))
m= np.random.randint(101, size=(10,2))
print(m)

x,y= m[:,0], m[:,1]
r= np.sqrt(x**2+y**2)
t= np.arctan2(y,x)
print(r)
print(t)

[[ 7 73]
 [99 56]
 [ 5  6]
 [84 73]
 [68 15]
 [10 27]
 [21 95]
 [95  5]
 [40 33]
 [ 6 30]]
[ 73.33484847 113.7409337    7.81024968 111.28791489  69.63476143
  28.7923601   97.29337079  95.13148795  51.85556865  30.59411708]
[1.47519821 0.51478409 0.87605805 0.71544878 0.21711131 1.21609067
 1.35324221 0.05258306 0.68980004 1.37340077]


## Task 21
- create random 13x13 matrix, replace maximal element to zero

In [29]:
x= np.random.randint(5,size=(13,13))
x[np.where(x==np.max(x))] = 0
print(x)

[[2 0 1 3 0 0 0 1 0 1 0 3 0]
 [0 3 2 1 0 0 0 0 2 0 0 3 0]
 [1 2 0 1 2 0 0 1 1 0 1 2 2]
 [0 2 3 0 0 1 1 1 0 0 3 0 2]
 [0 1 0 1 3 1 1 2 2 0 0 2 3]
 [1 0 2 1 2 0 0 1 0 2 0 0 1]
 [2 1 3 3 0 0 0 1 2 1 2 0 2]
 [3 1 1 0 0 2 0 2 3 3 1 2 1]
 [0 0 1 0 0 0 2 1 0 1 2 0 0]
 [0 0 3 1 3 0 1 2 0 0 0 1 0]
 [3 1 1 1 0 1 0 2 0 0 0 0 3]
 [1 0 1 2 0 2 0 3 0 0 1 0 2]
 [1 0 2 0 2 0 0 3 3 3 1 3 0]]


## Task 22
- create two 1d arrays with random values
- make a Cauchy matrix from them $C (C_{ij} = \frac{1}{x_i - y_j})$

In [71]:
x= np.random.standard_cauchy(size=10)
print(x)

[  0.3569221    1.07994101   0.12661266   1.06582828 -26.21989978
  -0.58829702   1.03283462   0.76168557  -1.97541068   1.16318025]


## Task 23
- create an array of random `float` numbers and convert it to `int`

In [72]:
np.arange(2, 10, dtype=np.float).astype(int)

array([2, 3, 4, 5, 6, 7, 8, 9])

## Task 24
- create 1d array of numbers from 0 to 15
- put each of them in random positions inside 4x4 matrix

In [74]:
np.random.randint(16, size=(4,4))


array([[ 5, 15, 12,  8],
       [13, 12,  1,  7],
       [15,  3,  4, 10],
       [12, 12, 10, 15]])

## Task 25
- create random 100x50 matrix
- deduct avarage of each row from correspondatn rows

In [76]:
x= np.random.randint(5, size=(100,50))


mean= np.mean(x, axis=1)


mean.shape

loop= mean.copy()
for i in range(x.shape[0]):
    loop[i] = loop[i] - mean[i]

loop.mean(axis=1)



np.mean(np.random.randint(5, size=(100,50)), axis=1)

array([1.94, 1.68, 2.08, 2.22, 2.2 , 2.12, 2.02, 2.12, 1.94, 1.9 , 2.04,
       2.04, 2.  , 1.84, 2.  , 2.3 , 1.84, 2.2 , 2.06, 1.92, 1.7 , 1.6 ,
       1.74, 1.9 , 1.96, 2.26, 2.26, 2.26, 1.54, 1.98, 1.98, 2.  , 2.04,
       1.96, 1.84, 2.1 , 1.88, 2.24, 1.92, 2.08, 2.16, 1.82, 2.  , 1.72,
       1.98, 1.9 , 1.94, 1.9 , 2.1 , 1.9 , 1.98, 1.92, 2.2 , 2.36, 1.84,
       1.86, 1.86, 2.04, 2.26, 2.3 , 2.24, 2.06, 1.92, 2.16, 2.04, 2.08,
       1.98, 2.2 , 2.24, 1.52, 1.68, 1.94, 2.14, 1.92, 2.04, 2.24, 2.08,
       1.84, 1.9 , 1.92, 2.12, 1.96, 1.74, 2.2 , 2.14, 2.18, 1.94, 1.96,
       2.46, 2.28, 1.96, 1.94, 1.68, 2.12, 1.94, 2.4 , 2.02, 2.68, 1.92,
       1.92])

## Task 26 
- create random 10x10 matrix
- extract diagonal elements and put them into 1d array

In [57]:
x= np.random.randint(5, size=(10,10))
print(x)

[[1 1 0 4 3 3 1 3 1 2]
 [2 3 1 3 2 1 3 0 2 4]
 [3 1 1 2 1 4 3 3 0 1]
 [0 4 0 2 3 1 3 2 2 1]
 [4 1 4 1 0 0 0 3 2 3]
 [1 2 0 0 4 3 0 4 0 0]
 [0 0 3 0 0 4 2 3 3 3]
 [2 0 0 1 4 2 3 2 4 1]
 [1 0 2 0 1 1 4 2 0 3]
 [0 4 2 3 1 0 2 3 0 0]]


## Task 27
- given a vector `[1, 2, 3, 4, 5]`
- build a new vertor with three zeros between each element